# This workflow create a resource group for specific subscription
# CAUTION: When pushing, change file name to "create-rg.yml"

name: 'Workflow Testing'
#name: 'Create Resource Group'

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    workflow-testing:
    #create-rg:
        runs-on: ubuntu-latest
        environment: development

        steps:
            - name: 'Login to Azure'
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: 'Run Azure CLI commands'
              run: |
                  az account show
                  pwd
