# This workflow create a resource group for specific subscription
# CAUTION: When pushing, change file name to "create-rg.yml"

name: 'Workflow Testing'
#name: 'Create Resource Group'

on:
  workflow_dispatch:
    inputs:
      LOCATION:
        description: "Enter location of resource group"
        required: true
        default: "Japan East"
        type: choice
        options:
          - Japan East
          - East US
      SERVICE_NAME:
        description: "Enter service name"
        required: true
        default: "workspace"
        type: string
      ENV_NAME:
        description: "Enter environment name"
        required: true
        default: "Development"
        type: choice
        options:
          - Development
          - Integration
          - Staging
          - Production

permissions:
  id-token: write
  contents: read

jobs:
  workflow-testing:
  #create-rg:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: "Set environment variables"
        run: |
          # Generate system and abbreviated names for locations
          if [ "${{ github.event.inputs.LOCATION }}" = "Japan East" ]; then
            echo "LOCATION_SYSTEM=japaneast" >> $GITHUB_ENV
            LOCATION_SHORT=jpe1
          elif [ "${{ github.event.inputs.LOCATION }}" = "East US" ]; then
            echo "LOCATION_SYSTEM=eastus" >> $GITHUB_ENV
            LOCATION_SHORT=eus1
          else
            :
          fi

          # Generate abbreviated names for environments
          case "${{ github.event.inputs.ENV_NAME }}" in
            "Development")
            ENV_NAME_SHORT=dev
            ;;
            "Integration")
            ENV_NAME_SHORT=integ
            ;;
            "Staging")
            ENV_NAME_SHORT=stg
            ;;
            "Production")
            ENV_NAME_SHORT=prod
            ;;
          esac
          
          # Generate resource group name
          echo "RG_NAME=rg-${{ github.event.inputs.SERVICE_NAME }}-${ENV_NAME_SHORT}-${LOCATION_SHORT}-001" >> $GITHUB_ENV
          #重複排除
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Create resource group"
        run: az group create --location $LOCATION_SYSTEM --name $RG_NAME